[build-system]
requires = ["meson-python>=0.16", "Cython>=3.0.0", "meson>=1.4", "ninja"]
build-backend = "mesonpy"

[project]
name = "ManimPango"
dynamic = ["version"]
description = "Pango bindings for rendering text to SVG"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE", "packing/LICENSE.bin"]
authors = [
    {name = "The Manim Community", email = "contact@manim.community"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Cython",
]

[project.urls]
Homepage = "https://github.com/ManimCommunity/ManimPango"
Documentation = "https://manimpango.manim.community/"
Repository = "https://github.com/ManimCommunity/ManimPango"
Issues = "https://github.com/ManimCommunity/ManimPango/issues"

[tool.uv]
no-build-isolation = true

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[dependency-groups]
build = [
    "cython>=3.2.4",
    "meson>=1.10.1",
    "meson-python>=0.19.0",
    "ninja>=1.13.0",
]
dev = [
    { include-group = "build" },
    "pre-commit>=4.0",
    "pytest>=9.0.2",
]
docs = [
    { include-group = "build" },
    "furo",
    "sphinx",
    "sphinxext-opengraph",
]
