from __future__ import annotations

from manimpango.fonts.enums import Style, Variant, Weight

class _FontDescription:
    def __init__(
        self,
        family: str = None,
        size: int = None,
        style: Style = None,
        weight: Weight = None,
        variant: Variant = None,
    ) -> None: ...
    @property
    def family(self) -> str | None: ...
    @family.setter
    def family(self, family: str) -> None: ...
    @property
    def size(self) -> int: ...
    @size.setter
    def size(self, size: int) -> None: ...
    @property
    def style(self) -> Style: ...
    @style.setter
    def style(self, style: Style) -> None: ...
    @property
    def weight(self) -> Weight: ...
    @weight.setter
    def weight(self, weight: Weight) -> None: ...
    @property
    def variant(self) -> Variant: ...
    @variant.setter
    def variant(self, variant: Variant) -> None: ...
    @classmethod
    def from_string(cls, string: str) -> _FontDescription: ...
