from enum import Enum

class Style(Enum):
    NORMAL = ...
    ITALIC = ...
    OBLIQUE = ...

class Weight(Enum):
    NORMAL = ...
    BOLD = ...
    THIN = ...
    ULTRALIGHT = ...
    LIGHT = ...
    BOOK = ...
    MEDIUM = ...
    SEMIBOLD = ...
    ULTRABOLD = ...
    HEAVY = ...
    ULTRAHEAVY = ...

class Variant(Enum):
    NORMAL = ...
    SMALL_CAPS = ...
