from ..layout import Layout

class ImageRenderer:
    def __init__(
        self,
        width: int,
        height: int,
        layout: Layout,
        file_name: str,
    ): ...
    @property
    def file_name(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def stride(self) -> int: ...
    def render(self) -> None: ...
    def save(self, file_name: str = None) -> str: ...
    def get_buffer(self) -> object: ...
