class Color:
    def __init__(self, red: int, green: int, blue: int) -> None: ...
    def copy(self) -> Color: ...
    @property
    def red(self) -> int: ...
    @red.setter
    def red(self, red: int) -> None: ...
    @property
    def green(self) -> int: ...
    @green.setter
    def green(self, green: int) -> None: ...
    @property
    def blue(self) -> int: ...
    @blue.setter
    def blue(self, blue: int) -> None: ...
