name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython

    - name: Install System Dependency (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install libpango1.0-dev
        sudo apt install libcairo2-dev pkg-config python3-dev

    - name: Install System Dependency (MacOS)
      if: runner.os == 'macOS'
      run: |
        brew install pango
        brew install cairo
    - uses: msys2/setup-msys2@v2
      name: Install System Dependency (Windows)
      if: runner.os == 'windows'
      with:
        update: true
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-pango mingw-w64-x86_64-cairo mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip mingw-w64-x86_64-pkg-config
    - name: Run Tests (Windows)
      shell: msys2 {0}
      if: runner.os == 'windows'
      run: |
        python -m pip install --upgrade pip
        python -m pip install Cython pytest
        pip install .
        pytest
    - name: Run Tests (Non-Windows)
      if: runner.os != 'windows'
      run: |
        pip install .
        pytest
